### ISSUE TITLE
Let module send message by itself?

### ISSUE THREAD

**Issue by p0358** [concierge/Concierge#204] opened 2016-08-25 05:45 UTC
Seems like a module can send a message to the chat only as a reply to a command, which makes a lot of limitations. For example I was trying to write mail notifier module, which would automatically notify about new mails in selected chat room(s). I needed to write it as Hubot module (and it works with Hubot just fine), but it still wasn't working with Concierge (no robot.messageRoom function). I have to use Hubot because of it... Do you have any ideas/plans on implementing that? Or some workaround? Or anything? I know it might be harder than in Hubot because of multiple integrations you can use at once, but I think that providing integration name like "facebook" in a function parameter before topic ID would solve this problem.

**Comment by ParasDPain** [comment] 2016-08-25 05:52
It might potentially be possible to run a module the lifetime of the bot and have it perform some action every few seconds (checking for mail and sending a message). 
And I believe `platform.getApis` is able to return integration names.

**Comment by mrkno** [comment] 2016-08-25 06:02
What @ParasDPain says is correct, `platform.getApis` is our way of doing this. It returns an object similar to the following:
```javascript
{
    "facebook": {
        sendMessage: [function Function],
        ....
    },
    "slack": {
        sendMessage: [function Function],
        ....
    }
}
```

You could from this get a list of all loaded integrations using `Object.keys(apis)`. You can also use `api.sendMessageToMultiple` if you have an `api` object.

It would be good if your Hubot script just worked with no modification within Concierge, so if you have time to work out how to make it work that could be useful.

**Comment by p0358** [comment] 2016-08-25 07:30
@mrkno `robot.messageRoom` would be the only function needed. The module is in prototype state (it works though), I could even rewrite it to Concierge module format, this is what I would prefer, and it has support for config file which is much better than Hubot's variables that my Hubot can't read on my Windows machine for some reason... Then with some reminder module I could totally get rid of Hubot (those reminder modules from Hubot doesn't want to work with Concierge either :/). I think I'll make my mail notifier Concierge module when I figure out nice way to send messages to rooms by itself. Thank for info, it should be much easier now and I know that's possible now :)
Current part of code responsible for notifying on mails is:
`  mailListener.on("mail", function(mail, seqno, attributes){
    // do something with mail object including attachments
    //console.log("emailParsed", mail);
    // mail processing code goes here
    robot.logger.info("[hubot-mail-notifier2] Got new mail, processing...");
    var fromfield = [];
    for (var sender in mail.from) {
      fromfield.push(mail.from[sender].name + " <" + mail.from[sender].address + ">");
	}

    var date = moment(mail.headers.date);

    //let message = '\n';
    let message = /*'New email from: '*/'Nowa wiadomość od: ' + fromfield.join(", ") + '\n';
    message += /*'Date: '*/'Data: ' + date.fromNow() + ' <' + date.format("LLLL") + '>\n';
    message += /*'Subject: '*/'Temat: ' + mail.subject + '\n';
    message += '\n';
    message += mail.text;
	//message += '\n';

    for (var room in configuration.rooms) {
      **robot.messageRoom(configuration.rooms[room], message);**
      robot.logger.info("[hubot-mail-notifier2] Sent info about mail to room " + configuration.rooms[room]);
	}

	robot.logger.info("[hubot-mail-notifier2] Finished processing mail.");
  });`

**Comment by mrkno** [comment] 2016-08-25 08:16
@p0358 
> Edit: If you could reload a single module without restarting whole Concierge, that would be brilliant for debugging purposes.

KPM was recently updated to allow for just this use case. `/kpm reload <moduleName>` if I remember correctly.

**Comment by p0358** [comment] 2016-08-25 10:32
Maybe I'm doing something wrong, but...
```
//I know this code is a mess, but it's just for testing :)
var apis;
var CronJob = require('cron').CronJob;
/*var job = new CronJob('* * * * * *', function() {
   //console.debug(Object.keys(apis)); //CRITICAL ERROR
   console.debug(Object.keys("" + exports.platform.getApis)); //undefined 
  }, function () {
    //This function is executed when the job stops
  },
  true//, // Start the job right now 
  //timeZone // Time zone of this job. 
);*/

exports.load = function() {
    console.log('test');
    apis = exports.platform.getApis;
    console.log("exports.platform.getApis = " + exports.platform.getApis);
    console.debug(Object.keys("" + exports.platform.getApis)); //undefined 
    exports.platform.getApis["facebook"].sendMessage("test", "1172606122xxxxxx");
}

exports.unload = function() {
    //job.stop();
}
```
The result on load is:

> test
> exports.platform.getApis = undefined
> undefined
> TypeError: Cannot read property 'facebook' of undefined
>   at Platform.exports.load (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\test\test.js:19:27)
>   at Object.exports.loadModule (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\modules.js:107:21)
>   at Platform.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\kpm\src\commands\reload.js:22:24)
>   at Platform.exports.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\kpm\kpm.js:39:23)
>   at Platform._handleTransaction (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:40:40)
>   at Platform.onMessage (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:72:47)
>   at C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\integrations\integrations.js:22:18
>   at [object Object].listener (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\core_integrations\test.js:54:9)
>   at [object Object].Cli.parse (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:320:35)
>   at [object Object].<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:182:18)
>   at [object Object].defaultFn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:53:13)
>   at [object Object].fn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:217:23)
>   at Interface.<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:148:18)
>   at emitOne (events.js:90:13)
>   at Interface.emit (events.js:182:7)
>   at Interface._onLine (readline.js:211:10)
>   at Interface._line (readline.js:550:8)
>   at Interface._ttyWrite (readline.js:827:14)
>   at ReadStream.onkeypress (readline.js:106:10)
>   at emitTwo (events.js:100:13)
>   at ReadStream.emit (events.js:185:7)
>   at emitKeys (readline.js:1251:14)
>   at [object Generator].next (native)
>   at ReadStream.onData (readline.js:919:36)
>   at emitOne (events.js:90:13)
>   at ReadStream.emit (events.js:182:7)
>   at readableAddChunk (_stream_readable.js:153:18)
>   at ReadStream.Readable.push (_stream_readable.js:111:10)
>   at TTY.onread (net.js:531:20)

What am I doing wrong? Getting `platform.getApis` without `exports` was giving me `ReferenceError: platform is not defined`.

**Comment by mrkno** [comment] 2016-08-25 11:40
@p0358 the problem is that cause it is currently undocumented and until recently was called `getApis` I accidentally pointed you at the wrong function name. As can be seen in master [here](https://github.com/concierge/Concierge/blob/master/core/platform.js#L80), its now called `getIntegrationApis`.

Sorry about that, hope using the right method name fixes your problem.

**Comment by p0358** [comment] 2016-08-25 13:00
@mrkno Thanks, now that's closer to be working 👍
However, `Object.keys("" + exports.platform.getIntegrationApis())` results in "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14", which I think should be integration names, doing `exports.platform.getIntegrationApis` without `()` also results with numbers, but 0-369. My only integrations are facebook and test.
Trying to do `exports.platform.getIntegrationApis()["facebook"].sendMessage("test", "1172606122xxxxxx");` results in:

> TypeError: Cannot read property 'sendMessage' of null
>   at Platform.exports.load (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\test\test.js:20:52)
>   at Object.exports.loadAllModules (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\modules.js:123:35)
>   at Platform.start (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:143:32)
>   at Object.exports.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\startup.js:41:18)
>   at Platform.checkShutdownCode (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\startup.js:22:17)
>   at emitOne (events.js:90:13)
>   at Platform.emit (events.js:182:7)
>   at Platform.shutdown (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:171:18)
>   at Platform.exports.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\restart\restart.js:4:10)
>   at Platform._handleTransaction (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:40:40)
>   at Platform.onMessage (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:72:47)
>   at C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\integrations\integrations.js:22:18
>   at [object Object].listener (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\core_integrations\test.js:54:9)
>   at [object Object].Cli.parse (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:320:35)
>   at [object Object].<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:182:18)
>   at [object Object].defaultFn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:53:13)
>   at [object Object].fn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:217:23)
>   at Interface.<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:148:18)
>   at emitOne (events.js:90:13)
>   at Interface.emit (events.js:182:7)
>   at Interface._onLine (readline.js:211:10)
>   at Interface._line (readline.js:550:8)
>   at Interface._ttyWrite (readline.js:827:14)
>   at ReadStream.onkeypress (readline.js:106:10)
>   at emitTwo (events.js:100:13)
>   at ReadStream.emit (events.js:185:7)
>   at emitKeys (readline.js:1251:14)
>   at [object Generator].next (native)
>   at ReadStream.onData (readline.js:919:36)
>   at emitOne (events.js:90:13)
>   at ReadStream.emit (events.js:182:7)
>   at readableAddChunk (_stream_readable.js:153:18)
>   at ReadStream.Readable.push (_stream_readable.js:111:10)
>   at TTY.onread (net.js:531:20)
> 
> A critical error occurred while running. Please check your configuration or report a bug.

Oh, and the hubot module not working was hubot-remind-her, it was reporting missing function robot.load, I wasn't looking closely at it. (apart from missing messageRoom, which would give an error if it worked and I set up a reminder and it attempted to send a message).

> TypeError: robot.load is not a function
>   at new module.exports (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\hubot-remind-her\index.coffee:9:18)
>   at new Robot (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\hubot\robot.js:94:25)
>   at Object.exports.loadModule (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\hubotModule.js:105:16)
>   at loadModuleInternal (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\modules.js:47:45)
>   at Object.exports.loadAllModules (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\modules.js:115:18)
>   at Platform.start (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:143:32)
>   at Object.exports.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\startup.js:41:18)
>   at Platform.checkShutdownCode (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\startup.js:22:17)
>   at emitOne (events.js:90:13)
>   at Platform.emit (events.js:182:7)
>   at Platform.shutdown (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:171:18)
>   at Platform.exports.run (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\restart\restart.js:4:10)
>   at Platform._handleTransaction (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:40:40)
>   at Platform.onMessage (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\platform.js:72:47)
>   at C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\integrations\integrations.js:22:18
>   at [object Object].listener (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\core_integrations\test.js:54:9)
>   at [object Object].Cli.parse (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:320:35)
>   at [object Object].<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:182:18)
>   at [object Object].defaultFn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:53:13)
>   at [object Object].fn (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:217:23)
>   at Interface.<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\cline\index.js:148:18)
>   at emitOne (events.js:90:13)
>   at Interface.emit (events.js:182:7)
>   at Interface._onLine (readline.js:211:10)
>   at Interface._line (readline.js:550:8)
>   at Interface._ttyWrite (readline.js:827:14)
>   at ReadStream.onkeypress (readline.js:106:10)
>   at emitTwo (events.js:100:13)
>   at ReadStream.emit (events.js:185:7)
>   at emitKeys (readline.js:1251:14)
>   at [object Generator].next (native)
>   at ReadStream.onData (readline.js:919:36)
>   at emitOne (events.js:90:13)
>   at ReadStream.emit (events.js:182:7)
>   at readableAddChunk (_stream_readable.js:153:18)
>   at ReadStream.Readable.push (_stream_readable.js:111:10)
>   at TTY.onread (net.js:531:20)

Code of index.coffee:
```
Path = require 'path'

module.exports = (robot) ->
  path = Path.resolve __dirname, 'scripts'
  robot.load path
```
Seems like it uses `robot.load` instead of `robot.loadFile` most others use. Example from hubot-speed-test:
`robot.loadFile(scriptPath, script);`

**Comment by p0358** [comment] 2016-08-25 19:47
Oh, I see my stupid mistake 😆 Changing
`console.debug("Object.keys(\"\" + exports.platform.getIntegrationApis()) = " + Object.keys("" + exports.platform.getIntegrationApis()));`
to
`console.debug("Object.keys(\"\" + exports.platform.getIntegrationApis()) = " + Object.keys(exports.platform.getIntegrationApis()));`
made it show

> Object.keys("" + exports.platform.getIntegrationApis()) = facebook,test

Sorry, I am pretty bad in JavaScript. Then the next thing
`exports.platform.getIntegrationApis()["facebook"].sendMessage("test", "1172606122xxxxxx");`
started to work instead of making `Cannot read property 'sendMessage' of undefined` error after changing it to
```
var facebookAPI = exports.platform.getIntegrationApis()["facebook"];
facebookAPI.sendMessage("test", "1172606122xxxxxx");
```
I guess I can now start rewriting my module to Concierge/Kassy format 😄

**Comment by mrkno** [comment] 2016-08-26 00:28
@p0358 https://github.com/concierge/Concierge/pull/205 should in theory fix the Hubot problems you had. `hubot-remind-her` loads and works fine with these changes. Could you test `messageRoom`?

**Comment by p0358** [comment] 2016-08-26 15:29
@mrkno `hubot-remind-her` works fine and sends messages on correct integration (test/facebook), sending messages to correct thread won't be a problem, because each integration has usually very unique thread ID, until someone had integration using his own server where he has room ID 1, then messages could land in console as well, or that room. But overall it would be unlikely.
My older (but working) Hubot version of module loaded, but...
```
Ładowanie zakończono pomyślnie
Uruchamianie integracji...
Ładowanie integracji 'facebook'...      [GOTOWE]
Ładowanie integracji 'test'...  [GOTOWE]
System został uruchomiony. Witaj świecie! //System run, hello world
Missing i18n value for key "Does something. The unhelpful author didn't specify what." in {current: "pl", default:"en"}.
Concierge> info Logging in...
[hubot-mail-notifier2] Connected to IMAP server.
[hubot-mail-notifier2] Got new mail, processing...

/* deprecation warning cutten off */

CRITICAL ERROR WAS UNHANDLED:
TypeError: apis[Symbol.iterator] is not a function
  at Robot.messageRoom (C:\Users\p0358\Documents\facebook-chat-api\Kassy\core\modules\hubot\robot.js:265:51)
  at MailListener.<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\modules\hubot-mail-notifier\src\mail-notifier.js:73:13)
  at emitThree (events.js:110:13)
  at MailListener.emit (events.js:188:7)
  at MailParser.<anonymous> (C:\Users\p0358\Documents\facebook-chat-api\Kassy\node_modules\mail-listener2\index.js:112:20)
  at emitOne (events.js:90:13)
  at MailParser.emit (events.js:182:7)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)

info Logged in
info Request to reconnect
info Request to pull 1
info Request to pull 2
info Request to thread_sync
info Done logging in.
info Got answer in  2004
info Got answer in  365
```

When I enable fetchUnreadOnStart, which fetches all unread mails as soon as it connects to IMAP server and posts them as seen as it gets them... too soon - integrations are not yet ready. That worked in Hubot, because seems like Hubot loads its adapter before scripts. I need to test if it works when mails arrive as well, but I'll need a new mailbox for that. Hang on, I will edit it when I test it.
```

**Comment by p0358** [comment] 2016-08-26 17:38
Okay, it (sending messages quickly after module got loaded - fetchUnreadOnStart) breaks in Concierge module as well (not because of `robot.messageRoom` of course). I think loading integrations before modules wouldn't be stupid idea. Are there any drawbacks of that?

**Comment by mrkno** [comment] 2016-08-26 22:28
@p0358 the problem is actually that I stupidly used a `for...of` loop on an un-iterable object. Try again now and it might work.

**Comment by mrkno** [comment] 2016-09-04 01:25
Closing as only remaining problem is timing related - something that we have no ability to fix.

**Closed by mrkno** 2016-09-04 01:25 UTC
Labels: question
